services:
  db:
    build:
      context: ./database
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    image: postgres-ja-fts
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
    depends_on:
      - db
    environment:
      SQL_USERNAME: ${POSTGRES_USER}
      SQL_PASSWORD: ${POSTGRES_PASSWORD}
      SQL_PORT: 5432
    ports:
      - "${FLASK_PORT}:5000"
    volumes:
      - ./api:/src

volumes:
  postgres_data:
