services:
  db:
    build:
      context: ./database
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    image: postgres-ja-fts
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql

  api:
    build:
      context: ./api
    depends_on:
      - db
    volumes:
      - ./api:/src
    ports:
      - "${FLASK_PORT}:5000"

volumes:
  postgres_data:
