services:
  db:
    build:
      context: ./database
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      DB_ENVIRONMENT: ${DB_ENVIRONMENT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres-ja-fts
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
    depends_on:
      db:
        condition: service_healthy
    environment:
      SQL_USERNAME: ${POSTGRES_USER}
      SQL_PASSWORD: ${POSTGRES_PASSWORD}
      SQL_PORT: 5432
      FLASK_ENVIRONMENT: ${FLASK_ENVIRONMENT}
    ports:
      - "${FLASK_PORT}:5000"
    volumes:
      - ./api:/src

volumes:
  postgres_data:
