services:
  db:
    build:
      context: ./database
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s 
      timeout: 5s
      retries: 10
    image: postgres-ja-fts
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
    depends_on:
      db:
        condition: service_healthy
    environment:
      SQL_USERNAME: ${POSTGRES_USER}
      SQL_PASSWORD: ${POSTGRES_PASSWORD}
      SQL_PORT: 5432
    ports:
      - "${API_PORT}:8080"
    volumes:
      - ./api:/api

  web:
    build:
      context: ./web
    command: npm run dev -- --host
    depends_on:
      - api
    ports:
      - 5173:5173
    volumes:
      - ./web:/src
      - /src/node_modules
volumes:
  postgres_data:
